(function initZetaPrecheck(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }
  root.__zetaPrecheck = api;
})(typeof globalThis !== "undefined" ? globalThis : window, function buildZetaPrecheck() {
  "use strict";

  const DEMO_LATEX_FILES = Object.freeze([
    {
      file_path: "main.tex",
      content: String.raw`\section{Model}

\begin{definition}[Covariance operator]
Let $\sigma$ be a covariance matrix in $\mathbb{R}^{n \times n}$ for the random vector $X$.
\end{definition}

\begin{assumption}[Bounded observations]
Assume that $X$ has finite second moment and that $n \geq 2$.
\end{assumption}`,
    },
    {
      file_path: "results.tex",
      content: String.raw`\section{Risk Bound}

\begin{theorem}[Risk bound]
For every admissible estimator, $\tau^2 \leq \sigma^2 + \epsilon$.
\end{theorem}

\begin{lemma}[Concentration step]
Let $\sigma > 0$ be the scalar variance used in the concentration inequality.
\end{lemma}

The proof reuses $\sigma x$ from the covariance model but later treats $\sigma$ as scalar variance.

\begin{definition}[Stopping parameter]
Finally define $\tau$ as the stopping-time parameter for the estimator.
\end{definition}`,
    },
  ]);

  const CERTIFICATION_STATES = Object.freeze({
    NOT_CHECKED: {
      key: "not_checked",
      label: "Not checked",
      description: "Run Zeta Pre-Check to generate a prototype publishing readiness report.",
    },
    CHECKING: {
      key: "checking",
      label: "Checking",
      description: "Zeta is scanning the document and building a local review report.",
    },
    NEEDS_REVIEW: {
      key: "needs_review",
      label: "Needs Review",
      description: "Recommended author review: one or more high-severity prototype checks raised concerns.",
    },
    PRECHECK_PASSED: {
      key: "precheck_passed",
      label: "Pre-Check Passed",
      description: "Zeta Pre-Check Passed means no high-severity notation or verification warnings were detected by the current prototype checks.",
    },
    CERTIFIED_DEMO_MODE: {
      key: "certified_demo_mode",
      label: "Certified Demo Mode",
      description: "Certified Demo Mode - sample verification result generated from deterministic local demo data.",
    },
  });

  const REVIEWER_SUMMARY_STATES = Object.freeze({
    HEURISTIC_FALLBACK: {
      key: "heuristic_fallback",
      label: "Heuristic fallback",
      description: "Generated locally from deterministic pre-check diagnostics. No LLM provider was used.",
    },
    AI_GENERATED: {
      key: "ai_generated",
      label: "AI-generated",
      description: "Generated by an optional provider through Zeta's provider-neutral reviewer summary interface.",
    },
    UNAVAILABLE: {
      key: "unavailable",
      label: "Unavailable",
      description: "Reviewer summary could not be generated from the available document signals.",
    },
  });

  const LATEX_ENV_RE = /\\begin\{(definition|theorem|lemma|assumption|proposition|corollary)\}(?:\[([^\]]+)\])?([\s\S]*?)\\end\{\1\}/g;
  const MATH_BLOCK_RE = /\$\$([\s\S]+?)\$\$|\$([^$]+?)\$|\\\[([\s\S]+?)\\\]|\\\(([\s\S]+?)\\\)/g;
  const COMMAND_RE = /\\([A-Za-z]+)/g;
  const BUILTIN_COMMANDS = new Set([
    "begin", "end", "mathbb", "mathcal", "mathrm", "mathbf", "operatorname",
    "frac", "sqrt", "sum", "prod", "int", "lim", "log", "ln", "exp", "sin", "cos", "tan",
    "left", "right", "leq", "geq", "neq", "approx", "equiv", "times", "cdot", "to",
    "rightarrow", "leftarrow", "in", "notin", "subset", "subseteq", "forall", "exists",
    "epsilon",
  ]);

  function normalizeFiles(files) {
    if (!Array.isArray(files) || files.length === 0) {
      return DEMO_LATEX_FILES.map((file) => ({ ...file }));
    }
    return files
      .filter((file) => file && (file.file_path || file.filePath))
      .map((file, index) => ({
        file_path: String(file.file_path || file.filePath || `document-${index + 1}.tex`),
        content: String(file.content || ""),
      }));
  }

  function lineNumberAt(content, index) {
    return String(content || "").slice(0, Math.max(0, index)).split(/\r?\n/).length;
  }

  function compactWhitespace(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  function contextWindow(content, start, end, radius = 100) {
    const left = Math.max(0, start - radius);
    const right = Math.min(content.length, end + radius);
    return compactWhitespace(content.slice(left, right));
  }

  function lineContextAt(content, index) {
    const text = String(content || "");
    const lineStart = text.lastIndexOf("\n", Math.max(0, index - 1)) + 1;
    const nextLine = text.indexOf("\n", index);
    const lineEnd = nextLine === -1 ? text.length : nextLine;
    return compactWhitespace(text.slice(lineStart, lineEnd));
  }

  function inferSemanticType(symbol, context) {
    const text = String(context || "").toLowerCase();
    const normalized = String(symbol || "").replace(/^\\/, "").toLowerCase();
    if (/covariance|matrix|\\mathbb\{r\}\^\{?[^}]*\\times/.test(text)) return "matrix";
    if (/scalar|variance|learning rate|step size|>\s*0|<\s*0|real number/.test(text)) return "scalar";
    if (/stopping|time parameter|parameter/.test(text)) return "parameter";
    if (/measure|probability|sigma.?algebra/.test(text)) return "measure";
    if (/function|operator|map|mapping|\\to|\\rightarrow/.test(text)) return "function";
    if (/set|collection|\\subset/.test(text)) return "set";
    if (/vector|random vector/.test(text)) return "vector";
    if (normalized === "sigma") return "symbol";
    if (normalized === "tau") return "parameter";
    return "unknown";
  }

  function isDefinitionContext(context) {
    return /\b(let|define|defined|denote|where|called)\b/i.test(context)
      && /\b(be|as|is|are|by|for)\b/i.test(context);
  }

  function extractEnvironments(file) {
    const content = file.content;
    const results = {
      definitions: [],
      theorems: [],
      lemmas: [],
      assumptions: [],
    };
    let match;
    while ((match = LATEX_ENV_RE.exec(content)) !== null) {
      const env = match[1];
      const title = compactWhitespace(match[2] || env);
      const body = compactWhitespace(match[3] || "");
      const item = {
        kind: env,
        title,
        text: body,
        file_path: file.file_path,
        line: lineNumberAt(content, match.index),
      };
      if (env === "definition") results.definitions.push(item);
      if (env === "theorem" || env === "proposition" || env === "corollary") results.theorems.push(item);
      if (env === "lemma") results.lemmas.push(item);
      if (env === "assumption") results.assumptions.push(item);
    }
    return results;
  }

  function extractInlineAssumptions(file) {
    const assumptions = [];
    const sentenceRe = /(?:^|[.!?]\s+)((?:Assume|Suppose)\b[^.!?]+[.!?]?)/g;
    let match;
    while ((match = sentenceRe.exec(file.content)) !== null) {
      assumptions.push({
        kind: "assumption",
        title: "Inline assumption",
        text: compactWhitespace(match[1]),
        file_path: file.file_path,
        line: lineNumberAt(file.content, match.index),
      });
    }
    return assumptions;
  }

  function extractSymbols(file) {
    const symbols = [];
    let mathMatch;
    while ((mathMatch = MATH_BLOCK_RE.exec(file.content)) !== null) {
      const mathText = mathMatch.slice(1).find(Boolean) || "";
      const blockStart = mathMatch.index;
      const blockEnd = blockStart + mathMatch[0].length;
      const context = contextWindow(file.content, blockStart, blockEnd);
      const localContext = lineContextAt(file.content, blockStart);
      let commandMatch;
      while ((commandMatch = COMMAND_RE.exec(mathText)) !== null) {
        const command = commandMatch[1];
        if (BUILTIN_COMMANDS.has(command)) continue;
        const symbol = `\\${command}`;
        const definition = isDefinitionContext(localContext);
        symbols.push({
          symbol,
          file_path: file.file_path,
          line: lineNumberAt(file.content, blockStart),
          context_text: context,
          semantic_type: inferSemanticType(symbol, context),
          is_definition: definition,
        });
      }
    }
    return symbols;
  }

  function parseLatexProject(filesInput) {
    const files = normalizeFiles(filesInput);
    const parsed = {
      documents: files.map((file) => ({ file_path: file.file_path, content_length: file.content.length })),
      definitions: [],
      theorems: [],
      lemmas: [],
      assumptions: [],
      symbols: [],
    };

    for (const file of files) {
      const envs = extractEnvironments(file);
      parsed.definitions.push(...envs.definitions);
      parsed.theorems.push(...envs.theorems);
      parsed.lemmas.push(...envs.lemmas);
      parsed.assumptions.push(...envs.assumptions, ...extractInlineAssumptions(file));
      parsed.symbols.push(...extractSymbols(file));
    }

    return parsed;
  }

  function detectNotationDrift(symbols) {
    const defsBySymbol = new Map();
    for (const item of symbols || []) {
      if (!item.is_definition) continue;
      if (!defsBySymbol.has(item.symbol)) defsBySymbol.set(item.symbol, []);
      defsBySymbol.get(item.symbol).push(item);
    }
    const issues = [];
    for (const [symbol, defs] of defsBySymbol.entries()) {
      const knownTypes = Array.from(new Set(defs.map((item) => item.semantic_type).filter((type) => type && type !== "unknown" && type !== "symbol")));
      const files = Array.from(new Set(defs.map((item) => item.file_path)));
      if (knownTypes.length > 1 && files.length > 1) {
        issues.push({
          id: `notation-drift-${symbol.replace(/[^A-Za-z0-9]/g, "")}`,
          type: "notation_drift",
          severity: "warning",
          symbol,
          message: `Potential issue: ${symbol} appears with multiple meanings (${knownTypes.join(", ")}) across ${files.join(", ")}.`,
          definitions: defs.map((item) => ({
            file_path: item.file_path,
            line: item.line,
            semantic_type: item.semantic_type,
            context_text: item.context_text,
          })),
        });
      }
    }
    return issues;
  }

  function detectUndefinedSymbols(symbols) {
    const bySymbol = new Map();
    for (const item of symbols || []) {
      if (!bySymbol.has(item.symbol)) bySymbol.set(item.symbol, []);
      bySymbol.get(item.symbol).push(item);
    }
    const issues = [];
    for (const [symbol, uses] of bySymbol.entries()) {
      const definitions = uses.filter((item) => item.is_definition);
      const sortedUses = uses.slice().sort((a, b) => a.file_path.localeCompare(b.file_path) || a.line - b.line);
      if (definitions.length === 0) {
        const first = sortedUses[0];
        issues.push({
          id: `undefined-${symbol.replace(/[^A-Za-z0-9]/g, "")}`,
          type: "undefined_symbol",
          severity: "warning",
          symbol,
          message: `Heuristic warning: ${symbol} is used but no local definition was detected.`,
          first_use: {
            file_path: first.file_path,
            line: first.line,
            context_text: first.context_text,
          },
        });
        continue;
      }
      const firstDefinition = definitions.slice().sort((a, b) => a.file_path.localeCompare(b.file_path) || a.line - b.line)[0];
      const earlierUse = sortedUses.find((item) => !item.is_definition && (
        item.file_path.localeCompare(firstDefinition.file_path) < 0
        || (item.file_path === firstDefinition.file_path && item.line < firstDefinition.line)
      ));
      if (earlierUse) {
        issues.push({
          id: `used-before-definition-${symbol.replace(/[^A-Za-z0-9]/g, "")}`,
          type: "undefined_symbol",
          severity: "warning",
          symbol,
          message: `Recommended author review: ${symbol} is used before its detected definition.`,
          first_use: {
            file_path: earlierUse.file_path,
            line: earlierUse.line,
            context_text: earlierUse.context_text,
          },
          first_definition: {
            file_path: firstDefinition.file_path,
            line: firstDefinition.line,
            context_text: firstDefinition.context_text,
          },
        });
      }
    }
    return issues;
  }

  function analyzePrecheck(parsed, options = {}) {
    const notationWarnings = detectNotationDrift(parsed.symbols);
    const undefinedSymbols = detectUndefinedSymbols(parsed.symbols);
    const verificationIssues = Array.isArray(options.verificationIssues) ? options.verificationIssues : [];
    return {
      notationWarnings,
      undefinedSymbols,
      verificationIssues,
      allIssues: [...notationWarnings, ...undefinedSymbols, ...verificationIssues],
    };
  }

  function calculateReadinessScore(parsed, analysis) {
    let score = 100;
    score -= analysis.notationWarnings.length * 12;
    score -= analysis.undefinedSymbols.length * 10;
    score -= analysis.verificationIssues.length * 14;
    if (parsed.definitions.length === 0) score -= 5;
    if (parsed.theorems.length + parsed.lemmas.length === 0) score -= 5;
    if (parsed.assumptions.length === 0) score -= 4;
    return Math.max(0, Math.min(100, score));
  }

  function certificationStateFor(score, analysis, options = {}) {
    const highSeverity = analysis.allIssues.some((issue) => issue.severity === "error");
    if (options.checking) return CERTIFICATION_STATES.CHECKING;
    if (options.notChecked) return CERTIFICATION_STATES.NOT_CHECKED;
    if (options.demoMode && !highSeverity && score >= 75) return CERTIFICATION_STATES.CERTIFIED_DEMO_MODE;
    if (highSeverity || score < 75) return CERTIFICATION_STATES.NEEDS_REVIEW;
    return CERTIFICATION_STATES.PRECHECK_PASSED;
  }

  function readinessStatusFor(score, analysis) {
    const highSeverity = analysis.allIssues.some((issue) => issue.severity === "error");
    if (!highSeverity && score >= 90) return "Zeta Pre-Check Passed";
    if (!highSeverity && score >= 75) return "Nearly Submission Ready";
    return "Needs Author Review";
  }

  function topReviewerConcerns(analysis) {
    const concerns = analysis.allIssues.slice(0, 3).map((issue) => issue.message);
    while (concerns.length < 3) {
      concerns.push("Recommended author review: verify assumptions, definitions, and notation before submission.");
    }
    return concerns.slice(0, 3);
  }

  function suggestedFixes(analysis) {
    const fixes = [];
    if (analysis.notationWarnings.length) fixes.push("Rename or restate overloaded notation so each symbol has a stable meaning across files.");
    if (analysis.undefinedSymbols.length) fixes.push("Define symbols before first use, or add a notation table near the beginning of the paper.");
    if (analysis.verificationIssues.length) fixes.push("Review Lean or verifier diagnostics and update the affected theorem statements.");
    if (!fixes.length) fixes.push("Run a final author review and keep the generated report with the submission notes.");
    return fixes;
  }

  function issueTitle(issue) {
    if (!issue) return "Pre-Check issue";
    if (issue.type === "notation_drift") return `Potential notation drift: ${issue.symbol}`;
    if (issue.type === "undefined_symbol" && issue.first_definition) return `Used before definition: ${issue.symbol}`;
    if (issue.type === "undefined_symbol") return `Undefined symbol: ${issue.symbol}`;
    if (issue.type === "lean") return "Verifier diagnostic";
    return "Recommended author review";
  }

  function issueLocation(issue) {
    if (!issue) return "";
    const point = issue.first_use || (Array.isArray(issue.definitions) ? issue.definitions[0] : null);
    if (!point) return "";
    const file = point.file_path || point.defined_in || "current document";
    const line = point.line ? `:${point.line}` : "";
    return `${file}${line}`;
  }

  function issueSnippet(issue) {
    if (!issue) return "";
    if (issue.first_use?.context_text) return issue.first_use.context_text;
    if (issue.first_definition?.context_text) return issue.first_definition.context_text;
    const definition = Array.isArray(issue.definitions)
      ? issue.definitions.find((item) => item.context_text)
      : null;
    return definition?.context_text || "";
  }

  function whyIssueMatters(issue) {
    if (!issue) {
      return "Zeta could not associate a detailed explanation with this issue.";
    }
    if (issue.type === "notation_drift") {
      return "Submission risk: readers and reviewers may apply algebraic rules from one meaning of the symbol to a later, different meaning.";
    }
    if (issue.type === "undefined_symbol") {
      return "Submission risk: a reviewer may not know the intended type or role of the symbol when evaluating the theorem statement.";
    }
    return "Submission risk: this diagnostic may affect how the statement, assumptions, or proof are interpreted.";
  }

  function suggestedFixForIssue(issue) {
    if (!issue) return "";
    if (issue.type === "notation_drift" && issue.symbol === "\\sigma") {
      return "Rename the scalar variance parameter to `s` or `\\sigma^2`, or add a sentence explicitly distinguishing scalar `\\sigma` from the covariance matrix meaning.";
    }
    if (issue.type === "notation_drift") {
      return `Rename one use of ${issue.symbol}, or add a notation note that states each meaning before the affected theorem or lemma.`;
    }
    if (issue.type === "undefined_symbol") {
      return `Define ${issue.symbol} before its first theorem-level use, or move its definition above the statement where it first appears.`;
    }
    if (issue.type === "lean") {
      return "Review the verifier diagnostic and update the affected theorem statement or proof obligation.";
    }
    return "Add a local clarification near the affected statement before submission.";
  }

  function reviewerCommentForIssue(issue, index = 0) {
    const number = Number.isFinite(index) ? index + 1 : 1;
    const title = issueTitle(issue);
    const fix = suggestedFixForIssue(issue);
    const message = issue?.message || "Recommended author review before submission.";
    return `Reviewer Comment #${number}: ${title}. ${message} Recommended author action: ${fix}`;
  }

  function problemSymbolsForReport(report) {
    const symbols = new Map();
    const issues = report?.analysis?.allIssues || [];
    for (const issue of issues) {
      if (!issue?.symbol) continue;
      const key = issue.symbol;
      if (!symbols.has(key)) {
        symbols.set(key, {
          symbol: key,
          severity: issue.severity || "warning",
          title: issueTitle(issue),
          location: issueLocation(issue),
        });
      }
    }
    return Array.from(symbols.values());
  }

  function inDocumentReviewItems(report) {
    const issues = report?.analysis?.allIssues || [];
    return issues.map((issue, index) => ({
      id: issue.id || `precheck-issue-${index + 1}`,
      index,
      severity: issue.severity || "warning",
      type: issue.type || "precheck",
      symbol: issue.symbol || "",
      title: issueTitle(issue),
      message: issue.message || "Recommended author review before submission.",
      location: issueLocation(issue),
      snippet: issueSnippet(issue),
      whyThisMatters: whyIssueMatters(issue),
      suggestedFix: suggestedFixForIssue(issue),
      reviewerComment: reviewerCommentForIssue(issue, index),
      counterexample: counterexampleExplanationForIssue(issue),
    }));
  }

  function buildReviewerSummaryContext(report) {
    const parsed = report?.parsed || {};
    const analysis = report?.analysis || {};
    const items = inDocumentReviewItems(report);
    const diagnostics = items.map((item) => ({
      id: item.id,
      type: item.type,
      severity: item.severity,
      symbol: item.symbol,
      title: item.title,
      message: item.message,
      location: item.location,
      snippet: item.snippet,
      suggestedFix: item.suggestedFix,
    }));

    return {
      title: report?.title || "Zeta Journal Readiness",
      score: Number(report?.score) || 0,
      statusBadge: report?.statusBadge || "Not checked",
      certification: report?.certification || CERTIFICATION_STATES.NOT_CHECKED,
      demoMode: !!report?.demoMode,
      counts: report?.counts || {},
      mathEntities: {
        definitions: parsed.definitions || [],
        theorems: parsed.theorems || [],
        lemmas: parsed.lemmas || [],
        assumptions: parsed.assumptions || [],
        symbols: parsed.symbols || [],
      },
      diagnostics,
      verificationIssues: analysis.verificationIssues || [],
      notationWarnings: analysis.notationWarnings || [],
      undefinedSymbols: analysis.undefinedSymbols || [],
      repairs: report?.repairs || report?.repairInfo || [],
      lean: report?.lean || report?.leanInfo || {
        verificationIssues: analysis.verificationIssues || [],
      },
      suggestedFixes: report?.suggestedAuthorFixes || [],
      reviewLedger: report?.reviewLedger || [],
    };
  }

  function unavailableReviewerSummary(reason = "No reviewer summary signals are available yet.") {
    return {
      state: REVIEWER_SUMMARY_STATES.UNAVAILABLE,
      text: reason,
      bullets: [],
      usedSignals: [],
      generatedAt: new Date().toISOString(),
    };
  }

  function heuristicReviewerSummary(report) {
    if (!report?.parsed || !report?.analysis) {
      return unavailableReviewerSummary();
    }

    const context = buildReviewerSummaryContext(report);
    const issueCount = context.diagnostics.length;
    const entityText = `${context.mathEntities.definitions.length} definition(s), ${context.mathEntities.theorems.length + context.mathEntities.lemmas.length} theorem/lemma item(s), and ${context.mathEntities.assumptions.length} assumption(s)`;
    const lead = issueCount
      ? `Zeta found ${issueCount} potential submission ${issueCount === 1 ? "risk" : "risks"} across ${entityText}.`
      : `Zeta found no high-severity prototype warnings across ${entityText}.`;
    const topDiagnostics = context.diagnostics.slice(0, 2).map((item) => {
      const location = item.location ? ` at ${item.location}` : "";
      return `${item.title}${location}: ${item.suggestedFix}`;
    });
    const leanSignal = context.verificationIssues.length
      ? `Lean/verifier signal: ${context.verificationIssues.length} verification issue(s) should be reviewed.`
      : "Lean/verifier signal: no verifier issues were attached to this Pre-Check run.";
    const repairSignal = Array.isArray(context.repairs) && context.repairs.length
      ? `Repair signal: ${context.repairs.length} suggested repair item(s) are available.`
      : "Repair signal: deterministic author fixes are available for each detected issue.";
    const bullets = [
      lead,
      ...topDiagnostics,
      leanSignal,
      repairSignal,
    ].slice(0, 5);

    return {
      state: REVIEWER_SUMMARY_STATES.HEURISTIC_FALLBACK,
      text: `${lead} ${issueCount ? "Recommended author review should focus first on notation consistency and symbol introduction order." : "Recommended author review should still confirm assumptions and notation before submission."}`,
      bullets,
      usedSignals: ["unified diagnostics", "math entities", "suggested repairs", "Lean/verifier info"],
      generatedAt: new Date().toISOString(),
    };
  }

  function normalizeReviewerSummaryProviderResult(result) {
    if (!result) return null;
    const stateKey = typeof result === "object"
      ? (typeof result.state === "string" ? result.state : result.state?.key)
      : "";
    const state = stateKey && REVIEWER_SUMMARY_STATES[String(stateKey).toUpperCase()]
      ? REVIEWER_SUMMARY_STATES[String(stateKey).toUpperCase()]
      : stateKey === "unavailable"
        ? REVIEWER_SUMMARY_STATES.UNAVAILABLE
        : stateKey === "heuristic_fallback"
          ? REVIEWER_SUMMARY_STATES.HEURISTIC_FALLBACK
          : REVIEWER_SUMMARY_STATES.AI_GENERATED;
    if (typeof result === "string") {
      const text = compactWhitespace(result);
      if (!text) return null;
      return {
        state: REVIEWER_SUMMARY_STATES.AI_GENERATED,
        text,
        bullets: [],
        usedSignals: ["provider response"],
        generatedAt: new Date().toISOString(),
      };
    }
    if (typeof result === "object") {
      const text = compactWhitespace(result.text || result.summary || "");
      if (!text) return null;
      return {
        state,
        text,
        bullets: Array.isArray(result.bullets)
          ? result.bullets.map((item) => compactWhitespace(item)).filter(Boolean).slice(0, 6)
          : [],
        usedSignals: Array.isArray(result.usedSignals)
          ? result.usedSignals.map((item) => compactWhitespace(item)).filter(Boolean).slice(0, 8)
          : ["provider response"],
        generatedAt: result.generatedAt || new Date().toISOString(),
        providerName: result.providerName ? String(result.providerName) : undefined,
      };
    }
    return null;
  }

  async function generateReviewerSummary(report, options = {}) {
    if (!report?.parsed || !report?.analysis) {
      return unavailableReviewerSummary();
    }

    const provider = options.reviewerSummaryProvider || options.provider;
    if (typeof provider !== "function") {
      return heuristicReviewerSummary(report);
    }

    const context = buildReviewerSummaryContext(report);
    try {
      const result = await provider(context);
      return normalizeReviewerSummaryProviderResult(result) || heuristicReviewerSummary(report);
    } catch (_error) {
      if (options.providerFailureState === "unavailable") {
        return unavailableReviewerSummary("AI reviewer summary is unavailable because the backend LLM request failed or timed out.");
      }
      return heuristicReviewerSummary(report);
    }
  }

  function generateReviewLedger(parsed, analysis, options = {}) {
    const timestamp = options.timestamp || new Date().toISOString();
    const events = [
      {
        timestamp,
        title: "Document scanned",
        description: `${parsed.documents.length} LaTeX file(s) parsed for scientific pre-check.`,
        status: "success",
      },
      {
        timestamp,
        title: "Definitions extracted",
        description: `${parsed.definitions.length} definition(s), ${parsed.theorems.length} theorem(s), ${parsed.lemmas.length} lemma(s), and ${parsed.assumptions.length} assumption(s) detected.`,
        status: "success",
      },
      {
        timestamp,
        title: "Notation graph built",
        description: `${parsed.symbols.length} symbol occurrence(s) analyzed for semantic consistency.`,
        status: "success",
      },
    ];
    if (analysis.notationWarnings.length) {
      events.push({
        timestamp,
        title: "Drift warning detected",
        description: `${analysis.notationWarnings.length} notation drift warning(s) require recommended author review.`,
        status: "warning",
      });
    }
    if (analysis.undefinedSymbols.length) {
      events.push({
        timestamp,
        title: "Undefined symbol warning detected",
        description: `${analysis.undefinedSymbols.length} symbol(s) appear undefined or used before definition.`,
        status: "warning",
      });
    }
    events.push({
      timestamp,
      title: "Pre-Check report ready",
      description: "Prototype reviewer report generated from deterministic local checks.",
      status: analysis.allIssues.length ? "warning" : "success",
    });
    return events;
  }

  function counterexampleExplanationForIssue(issue) {
    if (!issue) {
      return "No issue selected. Run Zeta Pre-Check and choose a warning to generate a local explanation.";
    }
    if (issue.type === "notation_drift" && issue.symbol === "\\sigma") {
      return "Counterexample intuition: If sigma is a covariance matrix in one theorem but a scalar variance in a later lemma, expressions like sigma x and sigma^2 have different meanings. A matrix-vector product and scalar multiplication obey different algebraic rules, so later proof steps can silently become invalid.";
    }
    if (issue.type === "notation_drift") {
      return `Counterexample intuition: ${issue.symbol} is assigned multiple meanings. A proof step that is valid for one meaning may be invalid for another, so downstream algebra should be reviewed before submission.`;
    }
    if (issue.type === "undefined_symbol") {
      return `Counterexample intuition: ${issue.symbol} is used before Zeta can find a definition. A reader may instantiate it with the wrong object or type, which can change the truth conditions of the theorem.`;
    }
    return "Counterexample intuition: this warning can affect the assumptions or notation a reviewer uses to interpret the proof. Recheck the local definitions and theorem statement.";
  }

  function buildPrecheckReport(filesInput, options = {}) {
    const parsed = parseLatexProject(filesInput || (options.demoMode ? DEMO_LATEX_FILES : []));
    const analysis = analyzePrecheck(parsed, options);
    const score = calculateReadinessScore(parsed, analysis);
    const certification = certificationStateFor(score, analysis, options);
    const statusBadge = readinessStatusFor(score, analysis);
    const ledger = generateReviewLedger(parsed, analysis, options);
    const concerns = topReviewerConcerns(analysis);
    const fixes = suggestedFixes(analysis);
    const report = {
      title: "Zeta Journal Readiness",
      demoMode: !!options.demoMode,
      score,
      statusBadge,
      certification,
      counts: {
        definitionsDetected: parsed.definitions.length,
        theoremsLemmasDetected: parsed.theorems.length + parsed.lemmas.length,
        assumptionsDetected: parsed.assumptions.length,
        notationWarnings: analysis.notationWarnings.length,
        undefinedSymbols: analysis.undefinedSymbols.length,
        verificationIssues: analysis.verificationIssues.length,
      },
      parsed,
      analysis,
      topReviewerConcerns: concerns,
      suggestedAuthorFixes: fixes,
      reviewLedger: ledger,
      counterexample: counterexampleExplanationForIssue(analysis.allIssues[0]),
    };
    report.reviewerSummary = heuristicReviewerSummary(report);
    return report;
  }

  function markdownReviewerReport(report) {
    const lines = [
      "# Zeta Scientific Pre-Check Report",
      "",
      `Readiness score: ${report.score}/100`,
      `Certification state: ${report.certification.label}`,
      `Status: ${report.statusBadge}`,
      "",
      "## AI Reviewer Summary",
      "",
      `${report.reviewerSummary?.state?.label || REVIEWER_SUMMARY_STATES.UNAVAILABLE.label}: ${report.reviewerSummary?.text || "No reviewer summary available."}`,
      "",
      "## Summary",
      "",
      `Zeta scanned ${report.parsed.documents.length} file(s), detected ${report.counts.definitionsDetected} definition(s), ${report.counts.theoremsLemmasDetected} theorem/lemma item(s), and ${report.counts.assumptionsDetected} assumption(s).`,
      "",
      "## Top Issues",
      "",
      ...report.topReviewerConcerns.map((item) => `- ${item}`),
      "",
      "## Suggested Fixes",
      "",
      ...report.suggestedAuthorFixes.map((item) => `- ${item}`),
      "",
      "## Review Ledger",
      "",
      ...report.reviewLedger.map((event) => `- ${event.timestamp} [${event.status}] ${event.title}: ${event.description}`),
      "",
      "## Disclaimer",
      "",
      "This is a Zeta prototype scientific pre-check. It uses heuristic and optional AI-assisted checks to surface potential issues. It does not certify full mathematical correctness unless a specific statement has been independently verified by the configured verifier.",
    ];
    if (report.demoMode) {
      lines.splice(5, 0, "Mode: Demo Mode - sample verification result.");
    }
    return `${lines.join("\n")}\n`;
  }

  return {
    DEMO_LATEX_FILES,
    CERTIFICATION_STATES,
    REVIEWER_SUMMARY_STATES,
    parseLatexProject,
    analyzePrecheck,
    calculateReadinessScore,
    certificationStateFor,
    readinessStatusFor,
    generateReviewLedger,
    counterexampleExplanationForIssue,
    issueTitle,
    suggestedFixForIssue,
    reviewerCommentForIssue,
    problemSymbolsForReport,
    inDocumentReviewItems,
    buildReviewerSummaryContext,
    heuristicReviewerSummary,
    unavailableReviewerSummary,
    generateReviewerSummary,
    buildPrecheckReport,
    markdownReviewerReport,
  };
});
